### ISSUE TITLE
Add Internationalization to docs

### ISSUE THREAD

**Issue by fuguefoundation** [aredn/documentation#244]
# Internationalization and AREDN

## Overview

In an effort to make the AREDN network more globally accessible to non-English speaking communities, an upcoming PR proposes for the AREDN documentation to integrate `internationalization`. At a high level, this is can be a three-step process.

1. Pull request to add necessary libraries and changes to `conf.py` to facilitate a multi-language environment of the documentation.
2. Using Weblate or Transifex, establish an online capability (and associated change management/pull request process that feeds into the Github repository) that allows those proficient in a chosen foreign language to easily contribute their expertise in translating the AREDN documentation. 
3. In an iterative process, seek ways to expand and improve the workflow as more languages are integrated.

## Note

@fuguefoundation would like to assist with points 2 and 3 in an effort to support the AREDN project. Although .rst style docs are familiar, incorporating internationalization into an existing project requires me to lean on the documentation below. Very open to feedback from the core devs on best way to do this so everyone benefits!

## References

* [Localization of documentation](https://docs.readthedocs.io/en/stable/localization.html) in `Read the Docs`
* [sphinx-intl](https://sphinx-intl.readthedocs.io/en/master/quickstart.html) - translation support utility for Sphinx
* Integrating Internationalization with [Weblate](https://docs.weblate.org/en/latest/devel/starting.html) or [Transifex](https://developers.transifex.com/docs)
* [Managing Translations in Sphinx](https://docs.readthedocs.io/en/stable/guides/manage-translations-sphinx.html)

**Comment by minexixi** [comment]
Crowdin is also a good choice

**Comment by minexixi** [comment]
And I think the AREDN official website may could be localization
