### ISSUE TITLE
not an issue, rather an inquiry or discussion: streamlined, checklist-like additional documentation?

### ISSUE THREAD

**Issue by cybork42** [aredn/documentation#310]
Dear Steve and other readers.

Just lately I had to program another Mikrotik hAP lite for a ham colleague of mine. Me programming a hAP is like half a year ago, and guess what, I forgot nearly everything. Well, I'm getting older, but only skimming through the documentation, I overlooked too many **lethal details** that I only got it to work sitting in silence on my own, reading the whole text top to bottom to find what I was missing out on.

I could imagine having a verbose description (the style it is made today) is essential, and another "**checklist-like instruction list"** would be a helpful addition. (think about a Heathkit building instructions and the concept sections of a kit manual).

Would you guys be open to explore such an addition, or is this just nonsense?
Please comment and let me know.

Tnx and 73, Andreas.

**Comment by ab7pa** [comment]
Install checklists already exist.

**Comment by cybork42** [comment]
You are terribly right, I went over them scanning the page for the right section :-(
I might not be the only one with this "fate", but other than that, thi sis not an issue, the list is extremely close to what was on my mind :-)
Cheers and 73, Andreas.
