### ISSUE TITLE
Improve Supernode documentation.

### ISSUE THREAD

**Issue by Orv** [aredn/documentation#355]
Currently the supernode documentation reads

Supernode tunnels use port 5526 rather than the usual tunnel port of 5525. 

To correct a typo and expand the documentation, it should read something like

Supernode tunnels use a starting port of **6526** rather than the usual tunnel port of 5525.  Wireguard tunnels use one port per tunnel, as opposed to the single port legacy tunnels use.  If you run a supernode server, you'll have to forward a block of ports, starting at 6526, depending on how many supernode clients you expect to serve.

**Comment by ab7pa** [comment]
This is a screenshot of the [current documentation](https://docs.arednmesh.org/en/latest/arednGettingStarted/advanced_config.html#tunnel-server), which already references port 6526.
<img width="725" alt="Screenshot 2024-05-24 at 9 10 21 PM" src="https://github.com/aredn/documentation/assets/69524416/285aabb5-1f6a-469f-82e4-0a664e83fd5c">

**Comment by Orv** [comment]
I was referencing another place:

Before proceeding, make sure all the previous steps have been completed successfully. Now you should be able to connect to another Supernode using a tunnel. The easiest way to do this is to ask another Supernode owner for a set of tunnel client credentials. Your node can use either a client or server tunnel link. Supernode tunnels use port **5526** rather than the usual tunnel port of 5525. Supernode owners can be identified from the [Supernode Network Map](https://arednmap.xojs.org/)

So just the one minor port typo then.

**Comment by ab7pa** [comment]
Ah... good eye. That was the original "how to" article, so several things have changed since then.  I've updated the "how to" for the current information. THX

**Comment by ab7pa** [comment]
Closed as complete.
