### ISSUE TITLE
 Time Display Source

### ISSUE THREAD

**Issue by K5RA** [aredn/documentation#388]
According to the new UI documentation the Time display should have source shown in parentheses.  My display has time but no source.  
Time configuration shows NTP Server as us.pool.ntp.org with daily updates. 

System is hap ac lite with 20240823 nightly and R-Pi 5B with latest bookworm and  Chromium 126 browser.

**Comment by aanon4** [comment]
We should clarify in the docs that if no time source is given, the time has not been synced with either NTP or GPS.

**Comment by K5RA** [comment]
I just checked Time against my iPhone.  Differs by 14 minutes.  !!!  Changed NTP updates to hourly.  Will check again later.

**Comment by K5RA** [comment]
Just after the hour (GMT), my hap showed correct time and indicated sync to NTP.  The NanoLoco, DTD'd to the HAP, is almost 50 mins slow.  But the R-Pi5B attached to the hAP showed correct time long before HAP or NanoLoco.
