### ISSUE TITLE
Feature Request; Metric units

### ISSUE THREAD

**Issue by Linus-007** [aredn/documentation#399]
Is it possible to write in user-selectable settings for units of measure? International adoption might be easier. I sure wish I could see the distances in km.

**Comment by aanon4** [comment]
You'll see metric in countries which use metrics. It's automatically set based on your browser locale.

**Comment by ab7pa** [comment]
This feature is already part of the firmware, but feature requests like this should be requested in the **_aredn_** repository.  The [documentation](https://docs.arednmesh.org/en/latest/arednGettingStarted/node_status.html#center-column) already mentions it: "This value will be expressed in _miles_ or _kilometers_ based on the locale settings in the web browser."
