### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by Orv** [aredn/documentation#57]
Found this minor typo:

Signal Charts
There is a Charts button next to the node’s Signal **Stength** display, and clicking this button takes you to Signal Charts. This page shows RF signal information in both a realtime and an archived view. The default view shows the average signal of all connected stations in realtime.

**Comment by kc0euw** [comment]
Thanks, Orv.  PR#58 opened to fix this issue.

**Comment by kc0euw** [comment]
Feel free to close this issue, but open any others on issues like this that you identify.  Much appreciated!

**Comment by kc0euw** [comment]
Orv, please close this issue since it was fixed a couple of weeks ago.  THX
