### ISSUE TITLE
Revise Help doc page re: Grid Square

### ISSUE THREAD

**Issue by Orv** [aredn/documentation#64]
If AREDN github entry #534 is accepted
 
On Help Page Under Optional Settings -

**Change**
If you choose, you can specify your latitude, longitude, and gridsquare for location purposes. ...

**To**
If you choose, you can specify your latitude and longitude for location purposes.

**Comment by ae6xe** [comment]
closing, see https://github.com/aredn/aredn_ar71xx/issues/534 .
